---
- name: configure | create pganalyze config
  template:
    src: etc/pganalyze-collector.conf.j2
    dest: /etc/pganalyze-collector.conf
    owner: "{{ pganalyze_user }}"
    group: "{{ pganalyze_group }}"
    mode: 0640
  notify:
    - restart pganalyze-collector
